### PR TITLE
Better error message and update dependencies

### PR DESCRIPTION
**Pull request by jaumard**
To be compatible with last Trails version

### CODE REVIEW

**Comment by jaumard** [comment]
About https://github.com/trailsjs/trailpack/issues/31

**Comment by jaumard** [comment]
About https://github.com/trailsjs/trailpack/issues/31

**Comment by jaumard** [comment]
Fix https://github.com/trailsjs/smokesignals/issues/6

**Comment by jaumard** [comment]
@tjwebb up for this please :) will make trailpack debug much easier

**Comment by scott-wyatt** [comment]
Bump.

**Pull request merged**
